GET http://localhost:5074/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZTczMDU5ZS1kYjk1LTQwOTAtOTAyNi0xMmYxZWUyNjU1NjYiLCJnaXZlbl9uYW1lIjoiZmlyc3ROYW1lIiwiZmFtaWx5X25hbWUiOiJsYXN0TmFtZSIsImp0aSI6ImRhMTc1NmRhLTFiNzMtNDkwZS04OTkyLTdiZDQ5NTEwMWU4MCIsImV4cCI6MTY3MDE2NzE5MiwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.-RsTmpdiBWUy3V7xy26HgIqK0qCyD_-6QPQQvLER2J8 
